uistring:
    title: Green Meteor
    description: Giving important guides to using modules and themes for HumHub projects.
    copyright: 2017-2019 Green Meteor, Inc.
    github_button_location_page_bottom: false

favicon: ico/16x16.ico

theme: jekyll-theme-minimal
